import{a as E,S as I,i as a}from"./assets/vendor-BNibzuFn.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))e(r);new MutationObserver(r=>{for(const n of r)if(n.type==="childList")for(const d of n.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&e(d)}).observe(document,{childList:!0,subtree:!0});function t(r){const n={};return r.integrity&&(n.integrity=r.integrity),r.referrerPolicy&&(n.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?n.credentials="include":r.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function e(r){if(r.ep)return;r.ep=!0;const n=t(r);fetch(r.href,n)}})();const M="https://pixabay.com/api/",P="52388349-b652c0030e98c4b6e488e9cd6",y=15,_=E.create({baseURL:M,params:{key:P,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:y}});async function h(s,o=1){try{return(await _.get("",{params:{q:s,page:o}})).data}catch(t){throw t}}const u=document.getElementById("gallery"),p=document.getElementById("loader"),g=document.getElementById("load-more"),b=new I(".gallery a",{captionsData:"alt",captionDelay:250});function L(s,o=!0){const t=s.map(e=>`
    <a class="gallery__item" href="${e.largeImageURL}">
      <div class="photo-card">
        <img src="${e.webformatURL}" alt="${e.tags}" loading="lazy" />
        <div class="info">
          <p><b>Likes:</b> ${e.likes}</p>
          <p><b>Views:</b> ${e.views}</p>
          <p><b>Comments:</b> ${e.comments}</p>
          <p><b>Downloads:</b> ${e.downloads}</p>
        </div>
      </div>
    </a>
  `).join("");o?u.insertAdjacentHTML("beforeend",t):u.innerHTML=t,b.refresh()}function $(){u.innerHTML="",b.refresh()}function B(){p.classList.remove("hidden")}function v(){p.classList.add("hidden")}function w(){g.classList.remove("hidden")}function c(){g.classList.add("hidden")}const i={form:document.getElementById("search-form"),input:document.getElementById("search-input"),loadMoreBtn:document.getElementById("load-more"),gallery:document.getElementById("gallery"),loader:document.getElementById("loader")};let f="",l=1,m=0;i.form.addEventListener("submit",O);i.loadMoreBtn.addEventListener("click",R);async function O(s){s.preventDefault();const o=i.input.value.trim();if(!o){a.warning({title:"Увага",message:"Введіть пошуковий запит"});return}f=o,l=1,$(),c();try{B();const t=await h(f,l),{hits:e}=t;if(m=t.totalHits||0,!e||e.length===0){a.info({title:"Результат",message:"За вашим запитом нічого не знайдено"});return}L(e,!1),l*y<m?w():(c(),a.info({title:"Кінець",message:"We're sorry, but you've reached the end of search results."}))}catch(t){console.error(t),a.error({title:"Помилка",message:"Помилка запиту — перевірте консоль"})}finally{v()}}async function R(){l+=1;try{B(),i.loadMoreBtn.disabled=!0;const s=await h(f,l),{hits:o}=s;if(!o||o.length===0){c(),a.info({title:"Кінець",message:"We're sorry, but you've reached the end of search results."});return}L(o,!0);const t=i.gallery.querySelector(".photo-card");if(t){const{height:e}=t.getBoundingClientRect();window.scrollBy({top:e*2,behavior:"smooth"})}l*y>=m?(c(),a.info({title:"Кінець",message:"We're sorry, but you've reached the end of search results."})):w()}catch(s){console.error(s),a.error({title:"Помилка",message:"Помилка підвантаження"})}finally{i.loadMoreBtn.disabled=!1,v()}}
//# sourceMappingURL=index.js.map
