import{a as w,S as E,i as a}from"./assets/vendor-BNibzuFn.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))e(r);new MutationObserver(r=>{for(const s of r)if(s.type==="childList")for(const d of s.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&e(d)}).observe(document,{childList:!0,subtree:!0});function t(r){const s={};return r.integrity&&(s.integrity=r.integrity),r.referrerPolicy&&(s.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?s.credentials="include":r.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function e(r){if(r.ep)return;r.ep=!0;const s=t(r);fetch(r.href,s)}})();const I="https://pixabay.com/api/",M="52388349-b652c0030e98c4b6e488e9cd6",m=15,P=w.create({baseURL:I,params:{key:M,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:m}});async function h(n,o=1){try{return(await P.get("",{params:{q:n,page:o}})).data}catch(t){throw t}}const y=document.getElementById("gallery"),p=document.getElementById("loader"),g=document.getElementById("load-more"),S=new E(".gallery a",{captionsData:"alt",captionDelay:250});function b(n,o=!0){const t=n.map(e=>`
    <a class="gallery__item" href="${e.largeImageURL}">
      <div class="photo-card">
        <img src="${e.webformatURL}" alt="${e.tags}" loading="lazy" />
        <div class="info">
          <p><b>Likes:</b> ${e.likes}</p>
          <p><b>Views:</b> ${e.views}</p>
          <p><b>Comments:</b> ${e.comments}</p>
          <p><b>Downloads:</b> ${e.downloads}</p>
        </div>
      </div>
    </a>
  `).join("");o?y.insertAdjacentHTML("beforeend",t):y.innerHTML=t,S.refresh()}function _(){const n=document.querySelector(".gallery");n&&(n.innerHTML="")}function L(){p.classList.remove("hidden")}function B(){p.classList.add("hidden")}function v(){g.classList.remove("hidden")}function c(){g.classList.add("hidden")}const i={form:document.getElementById("search-form"),input:document.getElementById("search-input"),loadMoreBtn:document.getElementById("load-more"),gallery:document.getElementById("gallery"),loader:document.getElementById("loader")};let u="",l=1,f=0;i.form.addEventListener("submit",$);i.loadMoreBtn.addEventListener("click",O);async function $(n){n.preventDefault();const o=i.input.value.trim();if(!o){a.warning({title:"Увага",message:"Введіть пошуковий запит"});return}u=o,l=1,_(),c();try{L();const t=await h(u,l),{hits:e}=t;if(f=t.totalHits||0,!e||e.length===0){a.info({title:"Результат",message:"За вашим запитом нічого не знайдено"});return}b(e,!1),l*m<f?v():(c(),a.info({title:"Кінець",message:"We're sorry, but you've reached the end of search results."}))}catch(t){console.error(t),a.error({title:"Помилка",message:"Помилка запиту — перевірте консоль"})}finally{B()}}async function O(){l+=1;try{L(),i.loadMoreBtn.disabled=!0;const n=await h(u,l),{hits:o}=n;if(!o||o.length===0){c(),a.info({title:"Кінець",message:"We're sorry, but you've reached the end of search results."});return}b(o,!0);const t=i.gallery.querySelector(".photo-card");if(t){const{height:e}=t.getBoundingClientRect();window.scrollBy({top:e*2,behavior:"smooth"})}l*m>=f?(c(),a.info({title:"Кінець",message:"We're sorry, but you've reached the end of search results."})):v()}catch(n){console.error(n),a.error({title:"Помилка",message:"Помилка підвантаження"})}finally{i.loadMoreBtn.disabled=!1,B()}}
//# sourceMappingURL=index.js.map
